// Regenerates src/ui/fontsData.ts from assets/fonts/. Run after changing the
// bundled fonts: node scripts/genFontsData.mjs
import { readFileSync, writeFileSync } from 'fs';

const b64 = (p) => readFileSync(p).toString('base64');
const out = `// GENERATED by scripts/genFontsData.mjs from assets/fonts/ — do not edit.
// Open Sans Bold: SIL OFL 1.1 (assets/fonts/OpenSans-OFL.txt).
// TRTA Numbers Sharp: CC0 / SIL OFL dual license (assets/fonts/TRTANumbers-LICENSE.txt).

/** Base64 TTF, family "Open Sans", weight 700. */
export const OPEN_SANS_BOLD_B64 = '${b64('assets/fonts/OpenSans-Bold.ttf')}';

/** Base64 TTF, family "TRTA Numbers Sharp". */
export const TRTA_NUMBERS_SHARP_B64 = '${b64('assets/fonts/TRTANumbersSharp.ttf')}';
`;
writeFileSync('src/ui/fontsData.ts', out);
console.log('src/ui/fontsData.ts written');
